"use client";
import Image from "next/image";
import { useState } from "react";

type Character = { avatarId: number; name: string | null; iconUrl: string | null; level: number | null; constellation: number | null; friendship: number | null; stats: Record<string, number>; equipment: Array<{ itemId: number; type: string; level: number | null; refinement: number | null }> };
type Profile = { nickname: string | null; level: number | null; worldLevel: number | null; characters: Character[] };

export function GenshinProfileViewer() {
  const [uid, setUid] = useState(""); const [profile, setProfile] = useState<Profile | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function load() { setLoading(true); setError(null); try { const response = await fetch(`/api/genshin/profile?uid=${uid}`); const payload = await response.json(); if (!response.ok) setError(payload.error ?? "Profile lookup failed."); else setProfile(payload); } catch { setError("Profile lookup failed. Check your connection and try again."); } finally { setLoading(false); } }
  return <section className="mt-6 rounded-2xl border border-white/10 bg-white/[0.035] p-5 sm:p-7"><p className="font-mono text-xs uppercase tracking-[0.18em] text-violet-300">In-site builds</p><h2 className="mt-2 text-2xl font-semibold text-white">Showcase characters</h2><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input inputMode="numeric" value={uid} onChange={(event) => setUid(event.target.value.replace(/\D/g, ""))} placeholder="Enter your 9-digit UID" className="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-3 text-sm text-white outline-none focus:border-violet-300/50" /><button type="button" onClick={load} disabled={loading || uid.length !== 9} className="rounded-xl bg-violet-300 px-4 py-3 text-sm font-semibold text-slate-950 hover:bg-violet-200 disabled:opacity-40">{loading ? "Loading…" : "Load builds"}</button></div>{error ? <p className="mt-4 rounded-lg border border-rose-300/20 bg-rose-300/10 px-3 py-2 text-sm text-rose-100">{error}</p> : null}{profile ? <div className="mt-6"><h3 className="text-xl font-semibold text-white">{profile.nickname ?? "Genshin showcase"}</h3><p className="mt-1 text-xs text-slate-500">Adventure Rank {profile.level ?? "—"} · World Level {profile.worldLevel ?? "—"}</p><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{profile.characters.map((character, index) => <details key={character.avatarId} className="rounded-xl border border-white/[0.08] bg-slate-950/60 p-4"><summary className="flex cursor-pointer items-center gap-3"><span className="grid size-10 place-items-center overflow-hidden rounded-lg bg-violet-300/10">{character.iconUrl ? <Image src={character.iconUrl} alt="" width={40} height={40} className="size-10 object-cover" unoptimized /> : <span className="text-xs font-bold text-violet-200">{index + 1}</span>}</span><span className="font-semibold text-white">{character.name ?? `Showcase character ${index + 1}`}</span><span className="ml-auto text-xs text-violet-200">Lv. {character.level ?? "—"}</span></summary><p className="mt-2 text-[10px] text-slate-600">Internal avatar ID {character.avatarId}</p><p className="mt-3 text-xs text-slate-500">Constellation {character.constellation ?? 0} · Friendship {character.friendship ?? "—"}</p><div className="mt-3 flex flex-wrap gap-1.5">{Object.entries(character.stats).map(([key, value]) => <span key={key} className="rounded-md border border-white/10 bg-white/[0.04] px-2 py-1 text-[10px] text-slate-300">{statLabel(key)}: {formatStatValue(key, value)}</span>)}</div><div className="mt-4 border-t border-white/[0.07] pt-3"><p className="text-[10px] uppercase tracking-wider text-slate-500">Equipment</p>{character.equipment.map((item) => <p key={`${item.type}-${item.itemId}`} className="mt-1 text-xs text-slate-300">{item.type} · level {item.level ?? "—"}{item.refinement ? ` · refinement ${item.refinement}` : ""}</p>)}</div></details>)}</div></div> : null}</section>;
}

function statLabel(key: string) { const labels: Record<string, string> = { "1": "Base HP", "2": "HP", "3": "HP%", "4": "Base ATK", "5": "ATK", "6": "ATK%", "7": "Base DEF", "8": "DEF", "9": "DEF%", "10": "Base SPD", "11": "SPD%", "20": "Crit Rate", "22": "Crit DMG", "23": "Energy Recharge", "26": "Healing Bonus", "27": "Incoming Healing", "28": "Elemental Mastery", "29": "Physical RES", "30": "Physical DMG", "40": "Pyro DMG", "41": "Electro DMG", "42": "Hydro DMG", "43": "Dendro DMG", "44": "Anemo DMG", "45": "Geo DMG", "46": "Cryo DMG", "81": "Shield Strength", "2000": "Max HP", "2001": "ATK", "2002": "DEF" }; return labels[key] ?? `Combat stat ${key}`; }
function formatStatValue(key: string, value: number) { const percentageKeys = new Set(["3", "6", "9", "11", "20", "22", "23", "26", "27", "29", "30", "40", "41", "42", "43", "44", "45", "46", "50", "51", "52", "53", "54", "55", "56", "81"]); return percentageKeys.has(key) ? `${(value * 100).toFixed(1)}%` : Math.round(value).toString(); }
