"use client";

import { startTransition, useEffect, useState } from "react";

type WishState = { total: number; characterPity: number; weaponPity: number; standardPity: number; primogems: number; uid: string };
const initialState: WishState = { total: 0, characterPity: 0, weaponPity: 0, standardPity: 0, primogems: 0, uid: "" };
const fieldClass = "mt-1.5 w-full rounded-lg border border-white/10 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-amber-300/50";

export function GenshinWishTracker() {
  const [state, setState] = useState<WishState>(initialState);
  const [ready, setReady] = useState(false);
  useEffect(() => { const saved = window.localStorage.getItem("gaming-tracker-genshin-wishes"); startTransition(() => { if (saved) { try { setState({ ...initialState, ...JSON.parse(saved) }); } catch { /* Ignore malformed local data. */ } } setReady(true); }); }, []);
  function update(key: keyof WishState, value: string) { setState((current) => ({ ...current, [key]: key === "uid" ? value : Math.max(0, Number(value) || 0) })); }
  function save() { window.localStorage.setItem("gaming-tracker-genshin-wishes", JSON.stringify(state)); }
  if (!ready) return <section className="h-64 rounded-2xl border border-white/10 bg-white/[0.035]" aria-label="Loading wish tracker" />;
  return <section className="rounded-2xl border border-white/10 bg-white/[0.035] p-5 sm:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-amber-300">Wish ledger</p><h2 className="mt-2 text-2xl font-semibold text-white">Your banner progress</h2></div><button type="button" onClick={save} className="rounded-xl bg-amber-300 px-4 py-2.5 text-sm font-semibold text-slate-950 hover:bg-amber-200">Save locally</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs text-slate-400">Total wishes<input type="number" min="0" value={state.total} onChange={(event) => update("total", event.target.value)} className={fieldClass} /></label><label className="text-xs text-slate-400">Character pity<input type="number" min="0" max="90" value={state.characterPity} onChange={(event) => update("characterPity", event.target.value)} className={fieldClass} /></label><label className="text-xs text-slate-400">Weapon pity<input type="number" min="0" max="80" value={state.weaponPity} onChange={(event) => update("weaponPity", event.target.value)} className={fieldClass} /></label><label className="text-xs text-slate-400">Standard pity<input type="number" min="0" max="90" value={state.standardPity} onChange={(event) => update("standardPity", event.target.value)} className={fieldClass} /></label></div><div className="mt-4 grid gap-4 sm:grid-cols-[1fr_auto] sm:items-end"><label className="text-xs text-slate-400">Primogems on hand<input type="number" min="0" value={state.primogems} onChange={(event) => update("primogems", event.target.value)} className={fieldClass} /></label><div className="rounded-xl border border-amber-300/15 bg-amber-300/[0.05] px-4 py-3 text-sm text-amber-100">{Math.floor(state.primogems / 160)} estimated wishes from primogems</div></div><div className="mt-8 border-t border-white/10 pt-6"><p className="font-mono text-xs uppercase tracking-[0.18em] text-violet-300">Akasha profile</p><label className="mt-3 block text-xs text-slate-400">Genshin UID<input inputMode="numeric" value={state.uid} onChange={(event) => update("uid", event.target.value.replace(/\D/g, ""))} placeholder="Enter your UID" className={fieldClass} /></label><div className="mt-3 flex flex-wrap gap-3"><a href={state.uid ? `https://akasha.cv/profile/${state.uid}` : "https://akasha.cv/"} target="_blank" rel="noreferrer" className="rounded-xl border border-violet-300/25 bg-violet-300/10 px-4 py-2.5 text-sm font-medium text-violet-100 hover:bg-violet-300/15">Open Akasha profile →</a><a href="https://akasha.cv/leaderboards" target="_blank" rel="noreferrer" className="rounded-xl border border-white/10 px-4 py-2.5 text-sm text-slate-300 hover:border-white/20 hover:text-white">Browse leaderboards</a></div></div></section>;
}
